const ActionType = {
  SET_USER: `SET_USER`,
  SET_OFFERS: `SET_OFFERS`,
  REMOVE_ALL_OFFERS: `REMOVE_ALL_OFFERS`,
  SET_ERROR: `SET_ERROR`,
  SET_REVIEWS: `SET_REVIEWS`,
  SET_ACTIVE_CITY: `SET_ACTIVE_CITY`,
  SET_ACTIVE_OFFERS: `SET_ACTIVE_OFFERS`,
  SET_ACTIVE_OFFER_ID: `SET_ACTIVE_OFFER_ID`,
  SET_FAVORITE_OFFERS: `SET_FAVORITE_OFFERS`,
  REMOVE_FAVORITE_OFFER: `REMOVE_FAVORITE_OFFER`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`
};

export default ActionType;
