export const SET_USER = `SET_USER`;
export const SET_OFFERS = `SET_OFFERS`;
export const SET_ACTIVE_CITY = `SET_ACTIVE_CITY`;
export const SET_ACTIVE_OFFERS = `SET_ACTIVE_OFFERS`;
export const SET_OFFER_BOOKMARK = `SET_OFFER_BOOKMARK`;
export const SET_ACTIVE_OFFER_ID = `SET_ACTIVE_OFFER_ID`;
export const SET_FAVORITE_OFFERS = `SET_FAVORITE_OFFERS`;
export const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
