export const SET_USER = `SET_USER`;

export const SET_OFFERS = `SET_OFFERS`;
export const REMOVE_OFFERS = `REMOVE_OFFERS`;

export const SET_REVIEWS = `SET_REVIEWS`;

export const SET_ACTIVE_CITY = `SET_ACTIVE_CITY`;

export const SET_ACTIVE_OFFERS = `SET_ACTIVE_OFFERS`;

export const SET_ACTIVE_OFFER_ID = `SET_ACTIVE_OFFER_ID`;

export const SET_FAVORITE_OFFERS = `SET_FAVORITE_OFFERS`;
export const REMOVE_FAVORITE_OFFER = `REMOVE_FAVORITE_OFFER`;

export const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
